version: "3"

services:
  phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      ports:
        - 8081:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: prestashop
      networks:
        - prestashop-net

  prestashop:
    image: prestashop/prestashop
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - PS_DEV_MODE=1
      - PS_DEMO_MODE=0
      - PS_INSTALL_AUTO=0
      - PS_DOMAIN=localhost:8082
      - PS_FOLDER_ADMIN=admin
      - PS_FOLDER_INSTALL=install
      - ADMIN_MAIL=demo@prestashop.com
      - ADMIN_PASSWD=prestashop_demo
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - prestashop-net
    volumes:
    - ./src/presta-vol/:/var/www/html:rw

  db:
    # platform: linux/x86_64 # uncomment for m1
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    volumes:
      - ./src/mysql-vol/:/var/lib/mysql
    networks:
      - prestashop-net

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
        context: ./nginx/
        dockerfile: Dockerfile
    ports:
        - 443:443
        - 8082:8082
        - 80:80
    volumes:
      - ./certs-volume/ca-cert.crt:/etc/nginx/ssl/ca-cert.crt
      - ./certs-volume/ca-key.key:/etc/nginx/ssl/ca-key.key
    networks:
      - prestashop-net
    depends_on:
      - prestashop


networks:
  prestashop-net: